### ISSUE TITLE
Book ready

### ISSUE THREAD

**Issue by FilipVel** [Notebook-Factory/cvxflow_book1#3]
Guys, just wanted to let you know that I finished editing this book. Please check if there is something that needs to be done additionally.

**Comment by mathieuboudreau** [comment]
Hi @FilipVel,

Here is my review:

* [ ] I updated the introduction text in the branch `review_mb`, which I just opened an issue for. Please rebuild the book using this update and then merge.
* [ ] Nikola asked an email (not sure if you were cc'd) that you guys add a logo for the journal Magnetic Resonance in Medicine in introduction (maybe the cover for the issue that this paper was published in).
* [ ] There's a need to distinguish the authors original github repository. I think you should link to that one under "GitHub Repository", or have a second one that links to "Original Code".
* [ ] The "Plotly Figures" section should be removed, and if you want to include that graph, it should be under "Demo code"
* [ ] Rename "Demo Code" to "Example"
* [ ] In each graph, change `trace0`->`Gx`, `trace1`->`Gy`, and `trace2`->`Gz`.
* [ ] In each graph, add a vertical axis title to be `Gradient (mT/m)`.
* [ ] In each graph, add a horizontal axis title to be `time (ms)`.

Thanks!

Mathieu
